# Generated by Django 5.1.4 on 2024-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
