# Generated by Django 5.1.4 on 2024-12-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0002_alter_chat_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='reciepient_user',
            new_name='reciepient',
        ),
    ]
