# Generated by Django 5.1.3 on 2024-12-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0003_rename_reciepient_user_chat_reciepient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='cover_image')),
                ('bio', models.TextField(max_length=1000)),
            ],
        ),
    ]
