# Generated by Django 5.1.3 on 2024-12-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0005_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
