# Generated by Django 5.1.3 on 2025-01-28 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0009_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('recipient')), _negated=True), name='prevent_self_message'),
        ),
    ]
