# Generated by Django 5.1.4 on 2025-02-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0010_chat_is_read_profile_location_profile_social_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
