# Generated by Django 5.1.6 on 2025-03-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0011_remove_profile_location_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
