# Generated by Django 5.1.6 on 2025-03-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0012_chat_delivered_at_chat_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
