# Generated by Django 5.1.6 on 2025-04-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0013_chat_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
