# Generated by Django 5.1.6 on 2025-04-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chattify', '0014_chat_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_id',
            field=models.UUIDField(auto_created=True, blank=True, editable=False, null=True, unique=True),
        ),
    ]
